[package]
name = "git-walker"
version = "0.1.0"
edition = "2018"

[dependencies]
memmap2 = "0.3.0"
byteorder = "1.4.3"
flate2 = { version = "1.0.20", features = ["zlib-ng-compat"], default-features = false }

[profile.release]
lto = true
opt-level = 3
